// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK46QvzT1Sk-YZHUsXgwe62uN9Un-b89Y',
    appId: '1:110342669459:android:3775ff63b111415cb63966',
    messagingSenderId: '110342669459',
    projectId: 'digital-cv-app-d06ff',
    storageBucket: 'digital-cv-app-d06ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jV9rbHRQ5BjjldBZiZkyHwLE_kO-tQU',
    appId: '1:110342669459:ios:19d6e81d2faef7a7b63966',
    messagingSenderId: '110342669459',
    projectId: 'digital-cv-app-d06ff',
    storageBucket: 'digital-cv-app-d06ff.firebasestorage.app',
    iosBundleId: 'com.example.digitalCvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4jV9rbHRQ5BjjldBZiZkyHwLE_kO-tQU',
    appId: '1:110342669459:ios:19d6e81d2faef7a7b63966',
    messagingSenderId: '110342669459',
    projectId: 'digital-cv-app-d06ff',
    storageBucket: 'digital-cv-app-d06ff.firebasestorage.app',
    iosBundleId: 'com.example.digitalCvApp',
  );

}